# Generated by Django 5.2.5 on 2025-10-12 16:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название болезни')),
                ('icd_code', models.CharField(blank=True, help_text='Код по МКБ-10/11', max_length=20, null=True, verbose_name='Код по МКБ-10/11')),
                ('type_origin', models.CharField(choices=[('infection', 'Инфекционное'), ('hereditary', 'Наследственное'), ('congenital', 'Врожденное'), ('physiological', 'Физиологическое'), ('traumatic', 'Травматическое'), ('malignant', 'Злокачественное'), ('deficit', 'Дефицитное'), ('autoimmune', 'Аутоиммунное'), ('endocrine', 'Эндокринное'), ('metabolic', 'Метаболическое'), ('degenerative', 'Дегенеративное'), ('mental', 'Психическое/Нервное'), ('unknown', 'Неизвестное/Идиопатическое')], max_length=100, verbose_name='Происхождение и природа')),
                ('type_localization', models.CharField(choices=[('eye', 'Глазные болезни'), ('ear_nose_throat', 'Болезни уха, горла и носа'), ('skin', 'Кожные болезни'), ('teeth_mouth', 'Стоматологические болезни'), ('heart_vascular', 'Болезни сердца и сосудов'), ('respiratory', 'Болезни органов дыхания'), ('digestive', 'Болезни органов пищеварения'), ('urinary', 'Болезни мочевыделительной системы'), ('reproductive', 'Болезни половой системы'), ('nervous', 'Заболевания нервной системы'), ('mental', 'Психические расстройства'), ('endocrine', 'Эндокринные заболевания'), ('immune', 'Аутоиммунные и иммунные нарушения'), ('musculoskeletal', 'Болезни костей, суставов и мышц'), ('infectious_general', 'Общие инфекционные болезни'), ('oncology', 'Онкологические болезни'), ('blood', 'Заболевания крови и кроветворных органов'), ('congenital', 'Врожденные аномалии'), ('metabolic', 'Нарушения обмена веществ')], max_length=100, verbose_name='Локализация болезни')),
                ('type_stimulant', models.CharField(choices=[('bacterial', 'Бактериальные'), ('viral', 'Вирусные'), ('fungal', 'Грибковые'), ('parasitic', 'Паразитарные'), ('toxic', 'Токсические (ядовитые вещества, химия)'), ('radiation', 'Радиация и излучение'), ('allergic', 'Аллергические реакции'), ('traumatic', 'Травматические факторы (физическое воздействие)'), ('autoimmune', 'Аутоиммунные'), ('genetic', 'Генетические мутации'), ('metabolic', 'Метаболические нарушения'), ('degenerative', 'Дегенеративные процессы (старение, разрушение тканей)'), ('neoplastic', 'Опухолевые (онкологические)'), ('unknown', 'Неизвестная причина / идиопатические')], max_length=100, verbose_name='Возбудитель')),
                ('type_process', models.CharField(choices=[('treatment', 'В процессе лечения'), ('cured', 'Вылечена')], max_length=20, verbose_name='Лечение')),
                ('desc', models.TextField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Болезни',
            },
        ),
        migrations.CreateModel(
            name='MedCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Медцентр/клиника')),
                ('type', models.CharField(choices=[('therapy', 'Терапия'), ('pediatrics', 'Педиатрия'), ('family', 'Семейная медицина'), ('geriatrics', 'Гериатрия (для пожилых)'), ('stomatology', 'Стоматология'), ('ophthalmo', 'Офтальмология (глазная клиника)'), ('otolaryngology', 'ЛОР (Отоларингология)'), ('derm', 'Дерматология'), ('allergy', 'Аллергология'), ('endocrinology', 'Эндокринология'), ('cardio', 'Кардиология'), ('gastro', 'Гастроэнтерология'), ('pulmo', 'Пульмонология'), ('neuro', 'Неврология'), ('psycho', 'Психиатрия / Психология'), ('urology', 'Урология'), ('gynecology', 'Гинеколог'), ('andrology', 'Андрология'), ('rheumatology', 'Ревматология'), ('infectious', 'Инфекционные заболевания'), ('oncology', 'Онкология'), ('hematology', 'Гематология'), ('nephrology', 'Нефрология'), ('surgery', 'Хирургия'), ('trauma', 'Травматология / Ортопедия'), ('plastic', 'Пластическая хирургия'), ('vascular', 'Сосудистая хирургия'), ('diagnostics', 'Диагностика / Анализы'), ('radiology', 'Радиология (КТ, МРТ, рентген)'), ('rehab', 'Реабилитация / ЛФК / Физиотерапия'), ('sports', 'Спортивная медицина'), ('cosmetology', 'Косметология'), ('dentistry', 'Зубопротезирование / Имплантология'), ('pain', 'Клиника боли'), ('emergency', 'Неотложная помощь'), ('multidisciplinary', 'Многопрофильный медцентр'), ('insurance', 'Страховая компания')], max_length=100, verbose_name='Тип медцентра')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Медцентр',
                'verbose_name_plural': 'Медцентры',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер телефона')),
                ('iin', models.CharField(max_length=12, unique=True, verbose_name='ИИН')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('role', models.CharField(choices=[('doc', 'Врач'), ('user', 'Пользователь')], max_length=10, verbose_name='Тип пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('medcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medcenter')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название анализа')),
                ('type', models.CharField(choices=[('cbc', 'Общий анализ крови (ОАК)'), ('biochemistry', 'Биохимический анализ крови'), ('coagulogram', 'Коагулограмма (анализ на свертываемость)'), ('urinalysis', 'Общий анализ мочи (ОАМ)'), ('stool', 'Копрограмма (анализ кала)'), ('hormones', 'Гормональные исследования'), ('allergy', 'Аллергопробы'), ('immunology', 'Иммунологические исследования'), ('microbiology', 'Микробиологические посевы'), ('pcr', 'ПЦР-анализ (ДНК/РНК диагностика)'), ('serology', 'Серологические тесты (антитела)'), ('oncomarkers', 'Анализ на онкомаркеры'), ('vitamins', 'Анализ на витамины и микроэлементы'), ('genetic', 'Генетические тесты'), ('functional', 'Функциональные тесты (глюкозотолерантный, дыхательный)'), ('toxicology', 'Токсикологические анализы'), ('infectious', 'Анализы на инфекции (ВИЧ, гепатиты, сифилис)'), ('covid', 'Анализ на COVID-19'), ('pregnancy', 'Тест на беременность (ХГЧ)'), ('other', 'Другое')], max_length=60, verbose_name='Тип анализа')),
                ('desc', models.TextField(max_length=1000, verbose_name='Описание/Информация')),
                ('medcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medcenter')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
        migrations.CreateModel(
            name='TestFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='tests/', verbose_name='Файл')),
                ('name', models.CharField(max_length=120, verbose_name='Название файла')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('blood_group', models.CharField(choices=[('0', 'O (I)'), ('A', 'A (II)'), ('B', 'B (III)'), ('AB', 'AB (IV)')], max_length=50, verbose_name='Группа крови')),
                ('rhesus_factor', models.CharField(choices=[('+', 'Положительный'), ('-', 'Отрицательный')], max_length=1, verbose_name='Резус-фактор')),
                ('bad_habits', models.TextField(blank=True, max_length=500, verbose_name='Вредные привычки')),
                ('psychoneurological_dispensary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pnd', to='core.medcenter')),
                ('rehab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rehabs', to='core.medcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь(данные)',
                'verbose_name_plural': 'Пользователи(данные)',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth'),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название операции')),
                ('desc', models.TextField(max_length=1000, verbose_name='Описание/Информация')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проведения')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease')),
                ('medcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='Номер полиса')),
                ('insurance_type', models.CharField(choices=[('mandatory', 'Обязательное медицинское страхование (ОМС)'), ('voluntary', 'Добровольное медицинское страхование (ДМС)')], max_length=30, verbose_name='Тип страховки')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(verbose_name='Дата окончания действия')),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма покрытия (₸)')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия страховки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Медицинская страховка',
                'verbose_name_plural': 'Медицинские страховки',
            },
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя препарата')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth')),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth'),
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вакцинации')),
                ('vac_name', models.CharField(max_length=100, verbose_name='Производитель вакцины')),
                ('desc', models.TextField(max_length=500, verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата вакцинации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=255, verbose_name='Причина визита')),
                ('desc', models.TextField(max_length=500, verbose_name='Описание')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата посещения')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userhealth')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
