# Generated by Django 5.2.5 on 2025-11-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
        migrations.AlterField(
            model_name='action',
            name='allergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allergy_actions', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='action',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_actions', to='core.disease'),
        ),
        migrations.AlterField(
            model_name='action',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drug_actions', to='core.drugs'),
        ),
        migrations.AlterField(
            model_name='action',
            name='surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_actions', to='core.surgery'),
        ),
        migrations.AlterField(
            model_name='action',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_actions', to='core.test'),
        ),
        migrations.AlterField(
            model_name='action',
            name='vaccination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_actions', to='core.vaccination'),
        ),
        migrations.AlterField(
            model_name='action',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_actions', to='core.visit'),
        ),
    ]
