# Generated by Django 5.2.5 on 2025-12-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_action_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='medcenter',
            field=models.ForeignKey(default=28359769, on_delete=django.db.models.deletion.CASCADE, related_name='medcenter_actions', to='core.medcenter'),
            preserve_default=False,
        ),
    ]
