# Generated by Django 5.2.5 on 2025-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_action_medcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default='qwe', max_length=100, verbose_name='Название действия'),
            preserve_default=False,
        ),
    ]
