# Generated by Django 5.2.5 on 2025-12-30 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_action_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вакцинации'),
        ),
    ]
