# Generated by Django 5.2.5 on 2026-01-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vaccination_medcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='desc',
            field=models.TextField(default='qwe', max_length=500, verbose_name='Примечания'),
            preserve_default=False,
        ),
    ]
