# Generated by Django 5.2.5 on 2026-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_drugs_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfiles',
            name='name',
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('cbc', 'Общий анализ крови (ОАК)'), ('biochemistry', 'Биохимический анализ крови'), ('coagulogram', 'Коагулограмма (анализ на свертываемость)'), ('urinalysis', 'Общий анализ мочи (ОАМ)'), ('stool', 'Копрограмма (анализ кала)'), ('hormones', 'Гормональные исследования'), ('allergy', 'Аллергопробы'), ('immunology', 'Иммунологические исследования'), ('microbiology', 'Микробиологические посевы'), ('pcr', 'ПЦР-анализ (ДНК/РНК диагностика)'), ('serology', 'Серологические тесты (антитела)'), ('oncomarkers', 'Анализ на онкомаркеры'), ('vitamins', 'Анализ на витамины и микроэлементы'), ('genetic', 'Генетические тесты'), ('functional', 'Функциональные тесты (глюкозотолерантный, дыхательный)'), ('toxicology', 'Токсикологические анализы'), ('infectious', 'Анализы на инфекции (ВИЧ, гепатиты, сифилис)'), ('covid', 'Анализ на COVID-19'), ('pregnancy', 'Тест на беременность (ХГЧ)'), ('xray', 'Рентгенография'), ('fluorography', 'Флюорография'), ('ct', 'Компьютерная томография (КТ)'), ('mri', 'Магнитно-резонансная томография (МРТ)'), ('ultrasound', 'Ультразвуковое исследование (УЗИ)'), ('echocardiography', 'Эхокардиография (ЭхоКГ)'), ('doppler', 'Допплерография'), ('angiography', 'Ангиография'), ('densitometry', 'Денситометрия (плотность костей)'), ('ecg', 'Электрокардиография (ЭКГ)'), ('holter', 'Холтеровское мониторирование'), ('spirography', 'Спирография'), ('eef', 'Электроэнцефалография (ЭЭГ)'), ('other', 'Другое')], max_length=60, verbose_name='Тип анализа'),
        ),
    ]
