# Generated by Django 5.2.5 on 2026-01-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_testfiles_name_alter_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='medcenter',
            field=models.ForeignKey(default=28359769, on_delete=django.db.models.deletion.CASCADE, to='core.medcenter'),
            preserve_default=False,
        ),
    ]
