# Generated by Django 5.2.5 on 2026-01-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_disease_medcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='medcenter',
            field=models.ForeignKey(default=28359769, on_delete=django.db.models.deletion.CASCADE, to='core.medcenter'),
            preserve_default=False,
        ),
    ]
