# Generated by Django 5.2.5 on 2026-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_drugs_medcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='ac_type',
            field=models.CharField(choices=[('edit', 'Редактирование'), ('add', 'Добавление')], default='add', max_length=5, verbose_name='Тип действия'),
        ),
    ]
