# Generated by Django 5.2.5 on 2026-06-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_action_ac_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_action', to='core.testfiles'),
        ),
    ]
