# Generated by Django 5.2.5 on 2026-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_action_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='files',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Действия с файлами'),
        ),
    ]
